- name: Install supercollider repo
  dnf:
    name: http://ccrma.stanford.edu/planetccrma/mirror/fedora/linux/planetccrma/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/planetccrma-repo-1.1-3.fc{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.ccrma.noarch.rpm
    disable_gpg_check: yes
    state: present
  become: yes
  tags:
    - supercollider

- name: Install supercollider
  dnf:
    name: supercollider
    state: present
  become: yes
  tags:
    - supercollider

- name: Install jack_lsp command
  dnf:
    name: jack-audio-connection-kit-example-clients
    state: present
  become: yes
  tags:
    - supercollider

- name: add user to audio group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: audio
    append: yes
  tags:
    - supercollider

- name: copy audio.conf
  become: yes
  copy:
    src: audio.conf
    dest: /etc/security/limits.d/audio.conf
    mode: 0644
    force: no
  tags:
    - supercollider

# - name: Install pipeaudio-jack
#   # (I think this is currently included with Fedora or might not be needed)
#   dnf:
#     name: pipewire-plugin-jack
#     state: present
#   become: yes
#   tags:
#     - supercollider

# - name: Install jackdbus
#   dnf:
#     name: jack-audio-connection-kit-dbus
#     state: present
#   become: yes
#   tags:
#     - supercollider
