- name: install mariadb
  become: yes
  dnf:
    name:
      - mariadb
      - mariadb-server
    state: present
  tags:
    - wordpress

- name: install php
  become: yes
  dnf:
    name:
      - php
      - php-common
      - php-mysqlnd
      - php-gd
      - php-xml
      - php-cli
      - php-opcache
      - php-mbstring
    state: present
  tags:
    - wordpress

- name: Install phpmyadmin
  dnf:
    name: phpmyadmin
    state: present
  become: yes
  tags:
    - wordpress
