- name: install mariadb
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb
    - mariadb-server
  tags:
    - wordpress

- name: install php
  become: yes
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-common
    - php-mysqlnd
    - php-gd
    - php-imap
    - php-xml
    - php-cli
    - php-opcache
    - php-mbstring
  tags:
    - wordpress

- name: Install phpmyadmin
  dnf:
    name: phpmyadmin
    state: present
  become: yes
  tags:
    - wordpress
