- name: Install emacs
  dnf:
    name: emacs
    state: present
  become: yes
  tags:
    - emacs

- name: remove old .emacs.d
  ansible.builtin.file:
    path: .emacs.d
    state: absent
  tags: emacs

- name: install emacs Live packs
  shell: "{{ item }}"
  with_items:
    - git clone https://github.com/josephfosco/emacs-live.git .emacs.d
    - make -C .emacs.d/packs/stable/org-pack/lib/org-mode autoloads
  args:
    chdir: $HOME
    creates: .emacs.d/init.el
  tags: emacs

- name: .emacs-live.el - custom live packs to load
  shell: "{{ item }}"
  with_items:
    - echo "(live-add-packs '(~/.live-packs/{{ ansible_user_id }}-pack))" > .emacs-live.el
  args:
    chdir: $HOME
    creates: .emacs-live.el
  tags: emacs

- name: add .live-packs directory
  ansible.builtin.file:
    path: $HOME/.live-packs
    state: directory
    mode: '0775'
  tags: emacs
