- name: Install emacs
  dnf:
    name: emacs
    state: present
  become: yes
  tags:
    - emacs

- name: remove old .emacs.d
  ansible.builtin.file:
    path: .emacs.d
    state: absent
  tags: emacs

- name: install emacs Live packs
  shell: "{{ item }}"
  with_items:
    - git clone https://github.com/josephfosco/emacs-live.git .emacs.d
    - make -C .emacs.d/packs/stable/org-pack/lib/org-mode autoloads
  args:
    chdir: $HOME
    creates: .emacs.d/init.el
  tags: emacs

- name: install emacs Live packs
  shell: "{{ item }}"
  with_items:
    # - mkdir --parents .live-packs/{{ ansible_user_id }}-pack
    # - cp -R .emacs.d/packs/template/user-template-pack .live-packs/{{ ansible_user_id }}-pack
    - git clone --recursive https://github.com/josephfosco/clj_init.el.git .live-packs/{{ ansible_user_id }}-pack
    - echo "(live-add-packs '(~/.live-packs/jfosco-pack))" > .emacs-live.el
  args:
    chdir: $HOME
    creates: .emacs-live.el
  tags: emacs
