---
# sets up bash profile for rbenv and installs ruby-build
- name: setup rbenv
  shell: |
    loop:
      echo '' >> ~/.bash_profile
      echo '# rbenv shims' >> ~/.bash_profile
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
      export PATH="$HOME/.rbenv/bin:$PATH"
      ~/.rbenv/bin/rbenv init
      echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
      mkdir -p "$(rbenv root)"/plugins
      git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
  args:
    chdir: $HOME
  tags:
    - ruby
