- name: install rlwrap for clojure
  become: yes
  dnf:
    name: rlwrap
    state: present
  tags:
    - clojure

- name: check if clojure is installed
  ansible.builtin.stat:
    path: /usr/local/bin/clojure
  register: clojure_installed
  tags:
    - clojure

# Downloads clojure with cli tools, and the next task installs
- name: download clojure cli tools install
  become: yes
  ansible.builtin.get_url:
    url: https://download.clojure.org/install/linux-install-1.11.1.1208.sh
    dest: /tmp/linux-install-1.11.1.1208.sh
    mode: 0755
  when: clojure_installed.stat.exists == False
  tags:
    - clojure

- name: execute clojure cli install
  become: yes
  shell: /tmp/linux-install-1.11.1.1208.sh
  when: clojure_installed.stat.exists == False
  tags:
    - clojure

- name: remove clojure cli installer
  become: yes
  file: path=/tmp/zsh-installer.sh
  args:
    state: absent
  tags:
    - clojure

# Install clj-new as a tool
- name:
  become: yes
  ansible.builtin.command:
    cmd: clojure -Ttools install com.github.seancorfield/clj-new '{:git/tag "v1.2.399"}' :as clj-new
  tags:
    - clojure

# NOTES
#
# Is there a way to still download and install clojure when changing the version
# or is there a way to always download the most current version of the installer
#
