# For some reason it seems installing the repo will crash
# if run after the repo is installed
# If this task needs to be rerun after the google-chrome
# repo is installed, the 'install google-chrome repo'
# step will need to be commented out

# - name: install google-chrome repo
#   become: yes
#   dnf:
#     name: 'https://google.com/chrome'
#     disable_gpg_check: yes
#     state: present
#   tags:
#     - google_chrome

- name: Download and install Google Chrome repo RPM
  become: yes
  dnf:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    disable_gpg_check: yes
    state: present

# install google-chrome
- name: install google-chrome
  become: yes
  dnf:
    name: google-chrome-stable
    enablerepo: google-chrome
    state: present
  tags:
    - google_chrome
